# Generated by Django 5.0.7 on 2024-07-16 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0001_initial'),
        ('user', '0003_users_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('transaction_type', models.CharField(choices=[('d', 'DEBIT'), ('c', 'CREDIT')], max_length=1)),
                ('amount_after_transaction', models.FloatField(default=0)),
                ('transaction_status', models.CharField(choices=[('p', 'PENDING'), ('s', 'SUCCESS'), ('r', 'REJECTED')], default='p', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_accounts.bank_account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
