# Generated by Django 5.0.7 on 2024-07-16 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_users_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.FloatField(default=0)),
                ('account_type', models.CharField(choices=[('sa', 'SAVINGS'), ('cu', 'CURRENT')], default='sa', max_length=2)),
                ('status', models.CharField(choices=[('a', 'ACTIVE'), ('i', 'IN_ACTIVE'), ('d', 'DELETED')], default='a', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.users')),
            ],
        ),
    ]
