# Generated by Django 5.0.7 on 2024-07-15 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=11)),
                ('phone_verified', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('a', 'ACTIVE'), ('i', 'IN_ACTIVE'), ('d', 'DELETED')], default='a', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
    ]
